### ISSUE TITLE
[LED] To implement RGB LED behaviour 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#101]
The new commboard will have only one RGB led instead of 2. This LED should display useful information for the user / installer in order to know how is the device. The following behaviour is proposed:

1. Bootloader : Red
2.  Bootloader - Downloading FW: Red blinking
3. Client app - TCP not connected: Yellow
4. Client app - TCP connecting : Yellow blinking (Blink in each GPRS or ETH step)
5. Client app connected to the broker: Green blinking (Blink in each main loop interaction, if exists, if not each second). If the connection is lost, 4. 
6. Client App: When the client app is in the scheduler task the led should blink in white
7. When a message arrives and during its process: Cyan, then again to 5.

The step 7 is optional. We implement like that in other products but maybe here with the RTOS is not possible.

**Comment by francisjjp** [comment]
![imagen](https://user-images.githubusercontent.com/18550654/36478342-a846c5dc-1704-11e8-89e2-7c86f42eef44.png)

This the connection for new revision PCB with RGB LED. The pins to use are PE3 PE4 PE5.

PE3, PE4, PE5 must be configurated as OPEN DRAIN (OD) and NO_PULL

**Comment by ralcaide** [comment]
@fpgamcu , I don't see any code the bootloader related with this issue. Will you upload that?

**Comment by fpgamcu** [comment]
Added next behavior:
In scheduler task blink white on each EPD processing.

**Comment by ralcaide** [comment]
Thanks, please verify that the description is correct.
@fpgamcu , Have you implemented last step?

**Comment by fpgamcu** [comment]
yes, step 7 is implemented.

**Comment by ralcaide** [comment]
The leds are working OK.
Closing the issue
