### ISSUE TITLE
[Time - RTC] Improve management of the current time of the device

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#105]
The time of the device is not very well managed. It is necessary to improve it. Problems:

- The RTC of the MCU is not used
- The time drift is very high / fast
- The scheduled actions are not well executed because of the time

Basically, the time source of the system is the RTC and should works as follow:

**INIT**

- Byt default, get time from NTP in **UTC**, if NTP server is available
- Time set by the user with the command 127; .This time is always **UTC**. If the time is set by the user, then should be maintained after reconnections / restarts. So, should be managed by a flag in the NVM
- Local offset: To be calculated and set when the GPS coordinates are set. If GPS coordinates are not set, then local offset is zero

**SYNCHRONIZATION**

- If time is set by user (127;) the time is not synchronized. 
- If the time is coming from NTP, then the RTC should be refreshed automatically:
1. After each reconnection
2. Every N hour. Configurable 

**USE**

- All the scheduled operations should be performed using **UTC** time
- Sunset / Sunrise is calculated everyday in **UTC**
- Local offset: In some operations should be applied the local offset. TO BE DESIGNED by RAE and ADA

Considerations:

- The offset should be recalculated each time that the GPS coordinates are set
- The time should be recalculated / corrected periodically if the RTC is not able to maintain the exact time. Related with #83

**Comment by ralcaide** [comment]
The time management should be simplified and improved asap. The CMC is not usable with the current time behaviour.

@fpgamcu, please provide us feedback & estimation

**Comment by fpgamcu** [comment]
Now the RTC is used in next way: after reconnection/reset time is got from NTP in UTC and set to the RTC, after used RTC to manage time.
I also noticed time drift and will check it reason.
Need to add, according to task description:
+ If the time is set by the user, then should be maintained after reconnections / restarts. So, should be managed by a flag in the NVM
+ Local offset: To be calculated and set when the GPS coordinates are set. If GPS coordinates are not set, then local offset is zero
+ If time is set by user (127;) the time is not synchronized.
+ If the time is coming from NTP, then the RTC should be refreshed automatically: Every hour and after reconnections / restarts
+ The offset should be recalculated each time that the GPS coordinates are set
+ The time should be recalculated / corrected periodically if the RTC is not able to maintain the exact time

Estimation is maximum 8 hours.

**Comment by ralcaide** [comment]
This is a crucial task for the correct behavior of AP, CMC and EN. Please tell us if you find any difficulties or  doubts

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task? Are you facing any problems?

**Comment by fpgamcu** [comment]
I have implemented it, in 2 hours I will push the code.

**Comment by fpgamcu** [comment]
I noticed that we have not implemented 127; command. Should it be implemented in this task also.

**Comment by ralcaide** [comment]
I think the 127; is implemented. At least it was tested with context AP. The command 127; should be available with any kind of context.

**Comment by fpgamcu** [comment]
Yes, sorry, It was done outside the context.

**Comment by fpgamcu** [comment]
Sorry for delay, there is several issues in current implementation:

Issues:
We have no offset management by now
Offset calculation by GPS coordinates is not done yet - databese of countries and timezones take several MB.
I will place databese on SD card and will try to use it, but not sure if it will work with such large files.


Limitations:
If each hour RTC correction by TIME server is enabled - device will reconnect each hour - it will take some time.
UTC offset now is integer in hours - that is why not possible to get UTC offset for timezone like +3:30

**Comment by ralcaide** [comment]
So, if I understand, now we have, 
- RTC in UTC always
- No offset
- Synchronization, each hour. How much time normally need this reconnection?.

**Comment by fpgamcu** [comment]
Depends of signal quality for GPRS (I think about a minute)
For ETH could be one or one and a half minute

**Comment by ralcaide** [comment]
Thanks. Updated the description. The synchronization frequency should be configurable and we will set this in compilation time, each hour is not acceptable. We will use normally each 6 hours or so or we will design a MQTT to update the RTC

Related with the offset: To save the database in the SD is not a good idea. Maybe there is an online service to get the offset sending the GPS coordinates, isn't?. If not, we will make this service

**Comment by fpgamcu** [comment]
Yes, there is several online services, but to work with them we should disconnect from MQTT before. If it is ok, I can implement it.

**Comment by ralcaide** [comment]
Yes, the offset should be calculated only when the GPS coordinates are set. This fact normally will be done one once

**Comment by fpgamcu** [comment]
Please check definitions.h file bottom for instructions on API key for UTC offset server.

**Comment by ralcaide** [comment]
@fpgamcu, can I set the label "To be tested" in this task?

**Comment by fpgamcu** [comment]
I think yes.
Offset calculation by GPS coordinates done using online service. By now offset still stored in the context as hours, but web service returns a seconds. So when we will implement offset management in #143 we could change offset in context to minutes to support time zones like India, etc.

**Comment by ralcaide** [comment]
Ok thank you. I understand now offset is calculated but not used, right? everything related with time is in UTC.

**Comment by fpgamcu** [comment]
yes

**Comment by ralcaide** [comment]
Quesiton: If the time is set with 127;, how can be used again the NTP instead the user time? How is this flag reset?

**Comment by ralcaide** [comment]
Problem:
after MQTT disconnection, the RTC have a big deviation.
![rtc_derive](https://user-images.githubusercontent.com/2856585/42212822-8788cf5a-7eb7-11e8-80fa-6535d4ccf803.png)
@fpgamcu , please try to improve this behavior

**Comment by ralcaide** [comment]
After three days of working, the RTC Time is not valid anymore.

![rtc_derive_weekend](https://user-images.githubusercontent.com/2856585/42214043-aed5bb92-7eba-11e8-8457-7161dc2dcdde.png)

What is the N by dafault?

**Comment by ralcaide** [comment]
Another not valid behaviour:
- time set with 127; -> OK
- Disconnect the device at HH:MM
- After XX:YY
- Time expected: HH+XX:MM+YY
- Time of the Device: Very close to HH:MM

Is this problem maybe related with the RTC battery?

**Comment by ralcaide** [comment]
@fpgamcu , all the problems related with RTC and time management have a very high priority. We will perform several modifications in the HW and this is the moment to detect any possible problem of possible improvement

**Comment by fpgamcu** [comment]
May be battery issue. But may be also some issue in the code. I will debug it. 
Also I will add in 127; possibility to reset flag with -1 parameters.

By the way, about hardware modifications, I have several questions:
1) What crystals now connected to the STM32?
2) Is there some external RTC on board?
3) How battery is connected to the STM32?

**Comment by ralcaide** [comment]
1. 
For MCU : 26 MHz
For MCU RTC: external crystal of 32768Hz

2. 
No

3. 
Connected to VBatt using Diode. We think the battery is well connected.

Questions:
- Are you using correctly the external crystal of 32Khz?
- Related with 127; after connection, are you getting the time from RTC with Get_RTC() or from Context?

**Comment by fpgamcu** [comment]
Should be used correctly. Getting time from RTC. I will check also configuration of rtc, maybe there is an issue.

**Comment by fpgamcu** [comment]
Have you measured battery current when testing battery circuit. When I measured I I got 79mA on 3.3V battery, it is huge. I am checking now SW side, could you share picture/pdf of battery circuit to check?

**Comment by fpgamcu** [comment]
I have some schematic, but not sure it is latest. Here is the problem:
![image](https://user-images.githubusercontent.com/17067442/42552517-5e52ee2a-84e5-11e8-8fae-dcd4a88a5b5d.png)
Leakage shown with the arrow

**Comment by fpgamcu** [comment]
Also DIO_ME_3 not necessary here, and RES_MI_19_7 also, they can consume some current and reduce battery life, but better will be to speak with Eugene.

**Comment by fpgamcu** [comment]
Also there was FW problem. Before last commit time was set on startup from backup registers, so there was effect of frozen time (time not tick in power off). Now I changed the code to use external crystal for RTC, not set time at startup - use time from RTC. Also on board I have removed RES_MI_19_2.

Checked with latest commit and removed RES_MI_19_2 - RTC is working when device is powered off.

**Comment by ralcaide** [comment]
Thanks, with the RES_MI_19_2 was not working?

**Comment by fpgamcu** [comment]
With RES_MI_19_2 battery current is 79mA so I think it was discharged by an hour or less.
Without this resistor current is about 1uA - 800nA so battery should live some time (need to calculate).

**Comment by francisjjp** [comment]
@fpgamcu .

-  Yes you must remove RES_MI_19_2 in order not to discharge all battery on VDD. 
- RES_MI_19_7 is added , and it is 0 ohms, there is not consumption there. In next hardware review two diodes will be placed in this way: VDD + DIODE -> VBATT and BATTERY + DIODE -> VBAT.
-  Devices in sinapse has placed only DIO_ME_3 and RES_MI_19_7 right, RES_MI_19_2 is not placed (This bug in assembly was corrected round 1-2 months), but drift time continues.

**Comment by soporteHW** [comment]
After several tests, it seems that RTC is working well.

With RTC configured through 127; API command, if device is power off for some time, after reconnection the device maintain a correct RTC value. So, the external battery is working.
See attached image:

![image](https://user-images.githubusercontent.com/28917446/43569674-7145c5de-9638-11e8-8118-cfef1056c8e9.png)

**Comment by soporteHW** [comment]
Although more stability tests will be performed, I included the label Status: tested passed.

**Comment by ralcaide** [comment]
@soporteHW , could we close this task?

**Comment by soporteHW** [comment]
Last test performed for EN device with FW V1.40.1

Test passed. Test result here: [RTC behaviour](https://sinapseenergia.testrail.io/index.php?/tests/view/1392)
