### ISSUE TITLE
[Customization] To develop customization of the AP signature

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#120]
Command and behavior here explained:

[Customize AP signature](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#customize-ap-signature)

**Comment by ralcaide** [comment]
Tested in T230

**Comment by ralcaide** [comment]
Please change the IDs of these commands in order to fit the wiki requirements:

209 - > 210
609 - > 610

**Comment by soporteHW** [comment]
Tested OK, Last FW V1.40.1

**EN device:**

![image](https://user-images.githubusercontent.com/28917446/47902007-9793e680-de81-11e8-8b2c-41145d8c46da.png)

**AP device**

![image](https://user-images.githubusercontent.com/28917446/47914781-1a786980-dea1-11e8-93c4-39990cde105c.png)
