### ISSUE TITLE
[L3 - Temperature and Humidity - On demmand] Develop MQTT L3 commands in order to get temperature and humidity from SHT1 sensor 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#135]
Develop the MQTT L3 commands in order to get the temperature and humidity from a sensor. By the moment the sensor to be used is the SHT1 but the sensor to use should be easy to modify in compilation time (Through a DEFINE)

**MQTT read Temperature and Humidity on demmand**

Question

Topic: `ID_INST/CMC/ACT/ID_AP` 
MSG: `L3_OD_TH;`

Response 

Topic: `ID_INST/CMC/MEASUREMENTS`
MSG: `L3_OD_TH_R;AP_ID;TEMPERATURE;HUMIDITY;TIMESTAMP;`

Task related with #133

**Comment by soporteHW** [comment]
Test done. Sensor SHT1 integration works fine.

Only a little BUG was found. TIMESTAMP param in MQTT msg response is wrong (sww attached image)
![sht1_sensor_test](https://user-images.githubusercontent.com/28917446/39988423-8e878f84-5767-11e8-8286-6369e9ed4024.png)

1357567428 equals 01/07/2013 @ 2:03pm (UTC)!!

**Comment by fpgamcu** [comment]
Thanks for the feedback, I will check the timestamp.

**Comment by soporteHW** [comment]
Another BUG found. The MQTT message reponse doesn't include the AP_ID to identify the device.

**Comment by ralcaide** [comment]
This is not a bug, is lack in the definition. 
I,ve modified the description of the issue in order to set add the AP_ID in the response message.

@fpgamcu , could you perform this little modification as soon as possible, please?. I think is very easy and fast, isn't?

**Comment by soporteHW** [comment]
Once restested this issue, the AP_ID now is included in the response message.
However, the TIMESTAMP is still bad.

Attached an image:

![image](https://user-images.githubusercontent.com/28917446/40437852-be6d6b0a-5eb6-11e8-8141-f44fe30a7c4f.png)

**Comment by soporteHW** [comment]
TIMESTAMP value fixed in BL V1.30.0 and CL V1.34
