### ISSUE TITLE
[Retrieve FW Version - 209;]  Ease the retrieving of the FW version 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#138]
Now, it is possible to retrieve the FW version using the commands 207; or 208; but these commands have other implications. Develop the command 209; in order to retrieve the FW version in an easy way:

[Retrieve FW version](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#retrieve-fw-version)

**Comment by ralcaide** [comment]
Because of this command is necessary to rename the Customization of the API: #120

**Comment by ralcaide** [comment]
To be tested through C133

**Comment by soporteHW** [comment]
The FW version wasn't sended
![image](https://user-images.githubusercontent.com/28917446/40484431-ecc80bb8-5f5b-11e8-878e-9533ea1c78fd.png)

**Comment by fpgamcu** [comment]
It was sent, but it is empty, since we do not have code anywhere to set it to some value.

**Comment by ralcaide** [comment]
This version should be set in the context, is not there?

**Comment by fpgamcu** [comment]
It is set to the context from shared with bootloader data, but in those data it is empty (bootloader is initializing those data on first time)

**Comment by ralcaide** [comment]
We are not able to update already installed bootloaders. It will be great to set the FW version from the client if it is empty. Also, the FW version in linked to the Client, not the bootloader. 
Is it possible to modify that, please?

**Comment by fpgamcu** [comment]
Yes, sure. I can add a code that will check the FW version in shred memory and set it to current FW version, if different. What format should be used for FW version, the same as the tag in the github?

**Comment by ralcaide** [comment]
@fpgamcu , status of this task?

**Comment by soporteHW** [comment]
Tested passed

**EN device**
![image](https://user-images.githubusercontent.com/28917446/48005765-90383b80-e114-11e8-8e48-1f4a9c4e74b5.png)

**AP device**
![image](https://user-images.githubusercontent.com/28917446/48005780-9cbc9400-e114-11e8-937e-0705c23f0e1e.png)
