### ISSUE TITLE
[ML1- API Command - 316] To implement the command "EPD Discovery"

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#14]
To implement the EPD Discovery (316;) command of the Sinapse API
Steps:

- Receive the command
- Save it in the MQTT_RECV_queue
- Process the command `316;ID;P;`
- The process create a new EPD in the Context with the correct ID and the Nominal Power

**Comment by ralcaide** [comment]
Closing the issue after TEST OK of #27

**Comment by ralcaide** [comment]
If a 313; is received but the EPD_ID already exist in the NVM the related data should stay as it is except the NOMINAL_POWER that should be updated. 
@fpgamcu , could you implement that please?

**Comment by fpgamcu** [comment]
@ralcaide Sure, will do it

**Comment by ralcaide** [comment]
@fpgamcu , how is going this feature?

**Comment by ralcaide** [comment]
TESTED OK
