### ISSUE TITLE
[CMC - Relay status] To maintain the relay status of the CMC

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#145]
The relay status are key in CMC product, therefore its status should be shared with the bootloader and maintained as soon as any reconnection / restart happens. The relay status should be centralized and applied as first step when the client application or the bootloader start. 

TODO:

- The relay status are in the context: Save them ALSO in the shared memory with the bootloader
- If the relay status is unknown (at the beginning), then is used OFF
- When the client application start, the relays should be set to the status saved in the shared memory
- When the bootloader application, the relays should be set to the status saved in the shared memory

Like that, the relays will be the most part of the time in the required status

**Comment by ralcaide** [comment]
@fpgamcu , this is a very important issue. Please provide us feedback

**Comment by fpgamcu** [comment]
For now I don't see any difficulties to implement this feature.
Estimation is 6 hours max.

**Comment by ralcaide** [comment]
Ok, great. Please be aware: Should be modified the Client app AND the Bootloader

**Comment by fpgamcu** [comment]
One remark:
Relay states will be saved into shared memory not at relay change but at each minute (with other device parameters), and only if it was changed. Like this we will have greatly reduced write count into shared memory.

**Comment by fpgamcu** [comment]
Very strange behavior, because we have a code to put relays in needed states as soon as possible. I client even before UART and other initialization, right after GPIO init.

**Comment by fpgamcu** [comment]
There was bug in relays code - absent conversion from ACTx to x and relay variables stay in 0. Now fixed.

**Comment by ralcaide** [comment]
I understand the last fix is only related with client program, isn't? How are the relays when the device is in bootloader mode?. During bootloader execution, the relays should have the last saved state. 

Should I create an issue bootloader project?

**Comment by fpgamcu** [comment]
It was an issue in client at saving relays into the NVM. Bootloader code is ok.

**Comment by ralcaide** [comment]
Yes, I know was an issue in client. But my question is: During bootloader execution, the relays maintain the last state set in the client? It is very important for a real installation to maintain always the expected relay state

**Comment by fpgamcu** [comment]
Yes, bootloader maintain the last state saved in the NVM. I have tested on my side. But please notice, that relays states is saved into the NVM with device parameters granularity (each minute).

**Comment by ralcaide** [comment]
Ok, thanks.

**Comment by ralcaide** [comment]
ON demmand tested passed: T367

Scheduler to be tesed: T368

**Comment by ralcaide** [comment]
During tests have been observed a not desired behaviour. The lights perform 1 or 2 ON/OFF cycles when the device is restarted with 398;. It will be great to avoid this behaviour. Maybe is related with the management of the GPIOs. In other program with legacy code, this "flicker" effect is not produced.

OLD CODE:

![maintenance_of_relays_status_oldfw](https://user-images.githubusercontent.com/2856585/43075072-c47b6756-8e7f-11e8-8e13-cbd088e24d9a.png)

NEW CODE:

![maintenance_of_relays_status_newfwv1 24 4](https://user-images.githubusercontent.com/2856585/43075086-cd9780b8-8e7f-11e8-8952-33c41c2506e6.png)

What do you think @fpgamcu ?

**Comment by soporteHW** [comment]
I performed new test with a Client FW modified as follow;

![image](https://user-images.githubusercontent.com/28917446/43135316-4aeff570-8f45-11e8-87eb-13430b26626e.png)

It seems that flickers disappears. Relays swtichs but the process is so fast that it is not appreciated in the lamp.

**Comment by fpgamcu** [comment]
Thanks for the suggestion. Please check also with the latest pushed code, it should do the trick :)

**Comment by soporteHW** [comment]
Hi, Sva. I checked your last commit and I saw that you set the gpio status before call the MX_GPIO_Initi(). 
Is this possible?

**Comment by fpgamcu** [comment]
Yes, it is exactly the way ST do in GPIO initialization, first setting state of GPIO and next init it to output.

**Comment by soporteHW** [comment]
OK, it's true. I saw that you changed too the GPIO_Init() function removing the RELAYS GPIO output level.
That's OK!

**Comment by soporteHW** [comment]
After some tests, I can conclude that:

1) Relays don't maintain their previous status for on demmand actuation. Test performed as follow:

![image](https://user-images.githubusercontent.com/28917446/43574263-fd398412-9643-11e8-95cb-ed75f916df61.png)

2) Relays maintain their previous status for scheduled actuation. Test performes as follow:

![image](https://user-images.githubusercontent.com/28917446/43574469-89a371d8-9644-11e8-87b8-ab5face40b6a.png)

About 2) there are some notes:
2.1 Relay outputs perform two switchings after reset (398;0;)
2.2 After sending 314; command, scheduled are erased but relay outputs maintain their previous status.

**Comment by ralcaide** [comment]
This feature is key in the CMC. 
@fpgamcu, are you able to reproduce the problems? We need this feature asap. Please provide feedback

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task? We need this feature

**Comment by fpgamcu** [comment]
Please test the relays on restart with the latest commit, it should fix the issue

**Comment by ralcaide** [comment]
Thanks, affects this modification to BL or only to the Client?

**Comment by fpgamcu** [comment]
Only client. Problem was only in client.

**Comment by soporteHW** [comment]
Tested passed. BUG fixed in V1.40.1

Test results here:
[Maintenance of relays status- On demand actuation](https://sinapseenergia.testrail.io/index.php?/tests/view/1102)

**NOTE:** two switchings are performed when device reboots
