### ISSUE TITLE
[CMC - Granularity of actuation] The CMC actuation should be executed in Real Time 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#148]
The granularity system implemented in the EN: #126 is not valid for CMC. The CMC should execute the actions in RT. 
Taking into account that the actions in CMC are done over only one device (Their relays) maybe is possible to avoid the granularity system over the actions related with CMC actuation. 

The command 10; should be executed in RT.

**Comment by ralcaide** [comment]
@fpgamcu , this is very important for the CMC product. What do you think?

**Comment by fpgamcu** [comment]
Implementing this feature should not be a problem, 4 hours should be enough to implement and test, but I think it can be finished even faster.

**Comment by ralcaide** [comment]
Related also with #144

**Comment by ralcaide** [comment]
OK Tested in T368
