### ISSUE TITLE
[Question] AP processing messages 1; but not sending response

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#156]
Strange behaviour in AP:

- We don't know if the EPD1 is setup or not
- Send question 1; to EPD1
- The AP publish the debug message 1; . So seems the message is in process
- The response 100; is never published
- Setup the EPD1; with 316; 
- Send question 1; to EPD1 -> Answer correctly

Is this behaviour normal? maybe was the EPD setup and now is corrupted?

**Comment by fpgamcu** [comment]
If response was not published, message was not processed. "Incoming message" debug output just means that there is a message and we is about to check it, and process only if valid. In #129 I have added commit that will make things more clear. If EPD ID will be wrong, there will be debug message like "999;Wrong ID".
