### ISSUE TITLE
[CMC][Interaction 10; - 11;] Develop interaction in between on-demand and scheduled commands

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#161]
It is necessary to develop the correct interaction between commands 10; and 11; in CMC.
At this moment, the scheduler is working with priority because the CMC set the scheduled value in each step, even if an on-demand action was received (not expected).

Steps:

- Add a new value to command 11;
- Implement interaction

[CMC - Interaction on-demand vs scheduler](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#interaction-between-actuation-ondemand-vs-scheduler)

**Comment by ralcaide** [comment]
@fpgamcu , could you give us a development estimation?

**Comment by fpgamcu** [comment]
3 hours should be enough

**Comment by ralcaide** [comment]
@fpgamcu , status of this task? Please provide feedback

**Comment by ralcaide** [comment]
Please, provide feedback

**Comment by soporteHW** [comment]
Testing results OK. Test passed
