### ISSUE TITLE
[BUG][Bootloader configuration][207; - 208; - 607;] Bootloader configuration commands are not working as expected

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#165]
This task is related with #119 and #134.

The command 607; is not working as expected after a 207; and 208;. 

The 607; should contains always the current values that will be used by the BL. These values are explained here:

[BL configuration](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#bootloader-configuration-information)

- To add FW_NAME: New added
- Response to 208; should be a valid 607. Now is:

![image](https://user-images.githubusercontent.com/2856585/43260326-72d63352-90d9-11e8-9928-5ff8a8b5f2d0.png)

- Response to 207; should be valid. For example, when only the UPDATE_FW is update we have the following response

![image 1](https://user-images.githubusercontent.com/2856585/43260399-a9d22b36-90d9-11e8-94f8-4f39357baa76.png)

Problem detected in 1.24

**Comment by soporteHW** [comment]
Tests performed here:

207) https://sinapseenergia.testrail.io/index.php?/tests/view/540
208) https://sinapseenergia.testrail.io/index.php?/tests/view/552

**Comment by ralcaide** [comment]
@fpgamcu , status of this task? Please provide feedback: reproducible? estimation?

**Comment by ralcaide** [comment]
Please, provide feedback

**Comment by fpgamcu** [comment]
Question about 607; response: I noticed that if some value is empty string (for example PATH) engine is not adding this parameter into response, so instead of `607;012345;0;1.30.3;www.dummy.org;80;HTTP;;a.bin;;;3;` we receiving `607;012345;0;1.30.3;www.dummy.org;80;HTTP;a.bin;3;`. Should I fix this behavior?

**Comment by ralcaide** [comment]
Yes please, the right option is the first one

**Comment by soporteHW** [comment]
Testing results OK. Test passed.
