### ISSUE TITLE
[BUG][API 5;] The connection to other broker is not well managed

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#172]
After some testing, the reconnection to other broker seems that work fine but after restart the device with 398;0; the device connects again to the original broker.

The device connects always to the original broker but the message is displaying the contingency broker.

![reconnection_fails_contingency](https://user-images.githubusercontent.com/2856585/45287660-19523e00-b4e9-11e8-8aee-fde3c7ae6494.png)

**Comment by fpgamcu** [comment]
Was bug here - displaying main broker address while connecting to backup broker.
Now when connect to backup broker will display backup broker address.

**Comment by soporteHW** [comment]
Tested with FW V1.40.1 => Test OK

Results here: [API 5; Change MQTT Broker credentials](https://sinapseenergia.testrail.io/index.php?/tests/view/1108)
