### ISSUE TITLE
[BROADCAST] The APs (CMCs & EN) should listen also in the Broadcast address and process the messages received

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#173]
Now, each AP has an ID (IMEI or MAC) and is listening there. It is necessary to set up also a broadcast address with ID FFFFFF, like that will be possible to act over N APs at the same time with only one command or for example to act over one EPD through N APs (if it is working in transparent mode).

Example:

ID_INST/FFFFFF/ACT/100101 3;100;

Will the a SET_ON to the device 100101 through all the APs with ID_INST

**Comment by fpgamcu** [comment]
Last commit should unlock possibility to use group AP id in EPD related commands. In other commands this feature was already implemented.

**Comment by ralcaide** [comment]
Thanks, will be tested

**Comment by soporteHW** [comment]
Tested in FW V1.40.1 => Test OK

Test results here: [Broadcast Features](https://sinapseenergia.testrail.io/index.php?/tests/view/1332)
