### ISSUE TITLE
[TH][L3 - Periodic] Develop L3 commands to read temperature & humidity periodically 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#178]
To develop the command

[Temperature & Humidity periodically](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/%5BExternal-Sensors%5D-MQTT-Sinapse-API#periodic)

Related with #135 and #177 

Like in #177, the default period should be customizable

**Comment by ralcaide** [comment]
I forgot to add the periodic command for T & H. @fpgamcu , please add it asap.

**Comment by soporteHW** [comment]
Tested OK in CL V1.40.0

Test here => [Temperature & Humidity - Periodically](https://sinapseenergia.testrail.io/index.php?/tests/view/1305)
