### ISSUE TITLE
[BUG][CMC - Metering] L3 metering function stop working in V1.40.1

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#179]
After the change performed in #100 like https://github.com/Sinapse-Energia/AP-Sinapse/commit/9f5be07325e2f7c911f3bf741837aa797591456a

The L3 command developed here #146 stop working.

**Comment by soporteHW** [comment]
It seems that ADDRESS MODBUS is harcoded as 0x01 in L3 functions

**Comment by fpgamcu** [comment]
Sure, checking now

**Comment by fpgamcu** [comment]
Address is set by Definitions.h CMC_ANALYZER_ADDRESS define to 1. Should it be set to some other address, or parameter to be used?

**Comment by ralcaide** [comment]
We will reformulate the commands in order to manage the different analyzers in a dynamic way directly from L3 commands.

Other question, is the current hardcoded value fitting the modifications of L1?

**Comment by ralcaide** [comment]
After testing: 
The EASTRON analyzers with Address = 0x01 are working OK.
The CIRCUTOR analyzers with Address = 0x01 are NOT working OK because this analyzer has a limitation in the number of bytes to read. Maximum is 80. The improvement of L3_Metering will be managed in other issue.
TODO by RAE

**Comment by ralcaide** [comment]
Solution will be provided through #180

**Comment by ralcaide** [comment]
Management to be done through #180
