### ISSUE TITLE
[CMC - Metering][Modbus] To include type and address into the L3 metering commands

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#180]
Related with #146 

Now, the FW is limited to use only ONE analyzer of ONE type (EASTRON) with a hardcoded address (0x01). This is a big limitation and is not linked with the reality of a bus. The bus MODBUS can have N devices connected to the same bus.

Speaking about metering, the CMC could have N analyzers (of different types) connected via RS485 and should be able to read each one in on demand & periodic modes

It is necessary to implement the new version of the next commands (Explained in the Wiki) and adapt the NVM to cover its requirements

- L3_READ_METERING_OD; 
- L3_READ_METERING_P; (NVM involved, to perform a good design or limitate) 
- L3_READ_METERING_R;

Wiki: [L3 Metering](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#ask-about-status-on-demand)

Two analyzers should be supported:

- EASTRON = 01 . Already implemented 
- CIRCUTOR = 02. To be implemented. DS in the master and accessible trough Wiki. It has a limitiation in reading, only 80 registers per reading are possible

**Comment by ralcaide** [comment]
Is this task "to be tested"?

**Comment by ralcaide** [comment]
Hello @fpgamcu, what is the status of this task? We are waiting for the CIRCUTOR analyzer code

**Comment by fpgamcu** [comment]
Sorry, was committed, but was not pushed

**Comment by ralcaide** [comment]
Ok, to be tested

**Comment by soporteHW** [comment]
Tested with EASTRON analyzer.
Results here: [CMC Metering L3 messages](https://sinapseenergia.testrail.io/index.php?/tests/view/1405)

It's necessary to test again using CIRCUTOR analyzer.

**Comment by soporteHW** [comment]
**Test performed:** AP device connected to 2 x EASTRON analyzer with ADDRESSES 01, 02 and the followgin configuration:
- EASTRON 01: connected L1 to read V1
- EASTRON 02: connected L1 and L2 to read V1 and V2

When I send "L3_READ_METERING_OD;01;01;" , the message returned is OK. Then, If I try to read the values from EASTRON 02 sending "L3_READ_METERTING_OD;01;02;" , the message returned includes the same values as previous message but BUS_ADDRESS = 02.

See the attached image.
![image](https://user-images.githubusercontent.com/28917446/49367938-bf2ed680-f6ed-11e8-8934-9ebf9c5ce50c.png)

However, If I perform several readings on the same device, the messages returned are OK.

**Comment by ralcaide** [comment]
It seems, in the NVM there is only space for one Network Analyzer, isn't @fpgamcu ?
The CMC should manage up to 8 analyzers, so it should be up to 8 analyzers in the NVM using a similar mechanism used in the EPDs.
The required development will be planned in other tasks.

**Comment by soporteHW** [comment]
**Test L3_METERING Periodically:** several cases performed as follow:

**- Case 1:** L3 _METERING periodically over an analyzer with ADD = 01

![periodic_overanalyzer01](https://user-images.githubusercontent.com/28917446/49371564-30738700-f6f8-11e8-9ae6-dd8dc367d2ce.png)

**Results:**  received 10 x L3_READ_METERING_R; messages as expected but message show BUS_ADDRESS = 0, and all the messages are the same (TIMESTAMP doesn't change)

**- Case 2:** L3 _METERING periodically over an analyzer with ADD = 02

![periodic_overanalyzer02](https://user-images.githubusercontent.com/28917446/49371648-7deff400-f6f8-11e8-9884-e290c8bd4893.png)

**Results:**  received 10 x L3_READ_METERING_R; messages as expected but message show BUS_ADDRESS = 0, and all the messages are the same (TIMESTAMP doesn't change)

**- Case 3:** L3 _METERING periodically over both analyzera with ADD = 01, 02

![periodic_over2analyzers](https://user-images.githubusercontent.com/28917446/49371718-b394dd00-f6f8-11e8-9211-0bcbe935d983.png)

**Results:** received 10 x L3_READ_METERING_R; messages from Analyzer ADD = 02, but messages show BUS_ADDRESS = 0, and all the messages are the same (TIMESTAMP doesn't change). Messages from Analyzer ADD = 01 are not received,

**- Case 3:** L3 _METERING periodically with scheduled in different days.

![image](https://user-images.githubusercontent.com/28917446/49371843-11292980-f6f9-11e8-8f85-b424afde2a74.png)

**Results:** L3_READ_METERING; messages are not received,

**- Case4:** L3_METERING periodically based on SR/SS => _NOT TESTED_

**Comment by ralcaide** [comment]
All the bad results are related with the fact that there are only one analyzer saved in the NVM, isn't @fpgamcu ?

**Comment by fpgamcu** [comment]
I think 8 hours should be enough to implement and test several analyzers feature. What parameter should be used as analyzer index? or it is a type of analyzer acting as index?

**Comment by ralcaide** [comment]
The analyzer index should be composed by TYPE+ADDRESS, for example if we have 2 Eastron and 2 Circutor the indexes cuold be:

0101, 0102, 0203 and  0204

See the commands in the Wiki, please.
At this moment, the periodic metering is not working at all.

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task?. Please provide feedback and estimation date

**Comment by fpgamcu** [comment]
We will continue fixing tomorrow, Ivan should finish it by the end of the Thursday.

**Comment by soporteHW** [comment]
What is the status of this issue? @fpgamcu @ralcaide

**Comment by ralcaide** [comment]
@fpgamcu, @ivan please update the status of this task

**Comment by soporteHW** [comment]
What is the status of this issue?

**Comment by ralcaide** [comment]
@fpgamcu , please provide feedback as soon as you can. Thanks

**Comment by ralcaide** [comment]
@fpgamcu , please provide feedback about the status of this task

**Comment by fpgamcu** [comment]
There is one limitation now: there can be only one scheduler for now, so setting another scheduler for Analyzers will erase previous one.
Please test the current code, if this one scheduler works ok on your side and if several analyzers on demand EPD like works ok on your side I will add scheduler for each analyzer, it is not hard modifications and should take not more that 2 hours.
If it is possible, please test last 2 commits one by one, 9fcb4d0 first and then 68992aa

**Comment by ralcaide** [comment]
Ok, we will test and provide you feedback

**Comment by soporteHW** [comment]
Tested with FW V19.8.0
Results here => [nombre](https://sinapseenergia.testrail.io/index.php?/tests/view/1498)

**Comment by soporteHW** [comment]
Tested with FW V19.8.0

Results here 
=> [Metering L3 messages On demand](https://sinapseenergia.testrail.io/index.php?/tests/view/1498)
=> [Metering L3 messages Periodically](https://sinapseenergia.testrail.io/index.php?/tests/view/1499)

**Comment by ralcaide** [comment]
Ok, it seems is working almost OK. The limitation found is well known. 
@fpgamcu , could you please fix / improve this limitation?

**Comment by fpgamcu** [comment]
yes, will fix the bug and add code removing limitation

**Comment by ralcaide** [comment]
@fpgamcu , status of this task?. Is fast & easy to add the limitation?

**Comment by ralcaide** [comment]
@fpgamcu , status of the task? Is easy / fast to remove the limitation?

**Comment by fpgamcu** [comment]
Need 6 hours more to remove limitation. Schedulers will work similar to EPD schedulers, with 10 minutes granularity

**Comment by ralcaide** [comment]
Thank you. We will test it and provide feedback

**Comment by soporteHW** [comment]
Tested: https://sinapseenergia.testrail.io/index.php?/tests/view/1624&group_by=cases:section_id&group_order=asc&group_id=170

Case 1: ADD = 01. Sended "L3_READ_METERING_OD;01;01;"

![image](https://user-images.githubusercontent.com/28917446/56489548-5ac8b400-64e2-11e9-912c-4b4d29f6d8ab.png)

Case 1 OK
Case 2: ADD = 02. Sended "L3_READ_METERING_OD;01;02;"
![image](https://user-images.githubusercontent.com/28917446/56489581-7c29a000-64e2-11e9-869e-e4870fe7c188.png)


Case 2 OK
Case 3: Alternative measurements between both analyzers
![image](https://user-images.githubusercontent.com/28917446/56489589-83e94480-64e2-11e9-8f39-06bb7ee1df3d.png)


Case 3 KO

I send ADD = 01. The response is ok. But, If I change ADD = 02, the first response return the data of the analyzer 1, the second response, is for the analyzer 2
