### ISSUE TITLE
[CMC][Relay status] Add relay status answer to acting relay commands (10; and 11;)

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#182]
The commands 10; and 11; don't have any answer. To add the relay status response to each actuation related with 10; and 11;

See new description

[Relay status after acting](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#act-over-relays-on-demand)

**Comment by soporteHW** [comment]
Tested failed. See results here: [#181](https://github.com/Sinapse-Energia/AP-Sinapse/issues/181)

BUGS:
- X feature is not working as expected
- TIMESTAMP value is always the same

**Comment by soporteHW** [comment]
TESTED. Related with [#181](https://github.com/Sinapse-Energia/AP-Sinapse/issues/181)

FW used BL V1.46.0 and CL V1.46.2

**Comment by ralcaide** [comment]
Tested OK

**Comment by ralcaide** [comment]
Tested OK
