### ISSUE TITLE
[USR][WIFI] To ease and secure the WIFI configuration method  

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#185]
USR is working great when WLAN_PERFORM_FIRST_CONFIG is NOT commented and we are working with DHCP or STATIC IP.
In order to use to connect the USR to WIFI, normally we comment the WLAN_PERFORM_FIRST_CONFIG and set the required configuration directly in the USR transceiver. This method has several problems:
1. The USR is restarted very frequently (each 30 secs?)
2. If the configuration is not well done before the USR restart, the USR saves the bad configuration and is not possible to access anymore to the configuration window. 

We need to find some solutions to the above problems and ease the WIFI configuration. Proposal:

a. Increase the restart time of the USR when the WLAN_PERFORM_FIRST_CONFIG is commented. This time should be enough to set the USR. I would say 3 minutes.
b. If the USR is not able to connect to the network after 5 tries, it should be restarted with its fabric values. Like that, if a configuration was wrong,  the user will always able to access the USR configuration page and try to configure it again

Any other improvement proposal is welcome

**Comment by fpgamcu** [comment]
Estimation is maximum 16 hours, but should be done faster. We will investigate additional time into it and finish on this weekend.

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task? We need an improvement on this part as soon as possible.
Then, we should design a mechanism in order to ease and improve the configuration of the device by an end user

**Comment by fpgamcu** [comment]
On final testing now. There is one bug with WiFi settings. I will fix it asap.

**Comment by ralcaide** [comment]
@fpgamcu , how is going this task? We will need the features explained in the description as soon as possible. Also, it would be great if additionally we can set the configuration of the USR directly in the SD card

**Comment by fpgamcu** [comment]
One question:
>  If the USR is not able to connect to the network after 5 tries, it should be restarted with its fabric values.

So it should keep its fabric values till the device reboot, not applying device_first_config values and not connecting to network?

**Comment by fpgamcu** [comment]
Or just restore fabric values and then proceed to connecting with it?

**Comment by ralcaide** [comment]
I don't understand very well. Normally when we connect using WIFI we comment the device_first_config and then we set the correct WIFI values directly in the USR Web application. The problem until now is that we have only 30 seconds to set the correct values and if the configuration was not correctly set then is not possible to set the configuration again. 

If I understand well your question I would say: Set fabric values and then continue as always

**Comment by fpgamcu** [comment]
Set fabric values and then continue as always, it is what I needed, thanks.

**Comment by fpgamcu** [comment]
Latest commit has next changes:
1) Using USR reset pin to reset USR before each connection - should work more stable with this
2) Time to wait for connection is now specified in WLCNT context variable (in seconds) and you can change it by editing DEV.TXT file on SD card
3) There is WLCNR variable in context. This variable is retries number for USR, after WLCNR retries USR will be reset to factory settings. Please ensure that FirstConfig is disabled, because if it is enabled after factory reset config parameters would be applied.
4) Most of USR configurations from FirstConfig function moved from Definitions to Context and can be edited by editing DEV.TXT on SD card.
WLCFG - perform(1) or not(0) FirstConfig
WLSRI and WLSRM - IP and Mask of internal USR web server
WLCLT - "static" or "DHCP" config
WLCLI, WLCLM, WLCLG - IP, Mask and Gateway for static config
WLCNT - time to wait for connect in seconds
WLCNR - retries count before factory reset

**Comment by ralcaide** [comment]
Thanks for the feedback.
Regarding your last comment: Not, this is not an option at this moment because the SD is not easily accessible. Normally the parameters will not be changed directly in the SD, it will be done only in very few cases where there is a problem. 
The goal in fact is to use the USR web server to set the configuration. 
To do that in a good way we need the implementation of your previous comment, not waiting a constant time but stop waiting when the connected is established.
When could be available this part of the code?

**Comment by fpgamcu** [comment]
I will finish it in an hour.

**Comment by ralcaide** [comment]
ok, so we wait to that in order to start testing

**Comment by ralcaide** [comment]
@fpgamcu , what about bootloader? Is this program also restarting the USR?

**Comment by fpgamcu** [comment]
This changes is not integrated into bootloader. Should I integrate them?

**Comment by ralcaide** [comment]
If the BL is not able to connect, then continue to the client program. Right?
Normally, the execution of the BL is disabled so should not be a problem. Let us test and I will tell you

**Comment by ralcaide** [comment]
@fpgamcu , how is now working the BL when the USR gateway is not well set? Is it worthwhile to include these changes into the BL?

**Comment by ralcaide** [comment]
@fpgamcu, could you please provide feedback about this issue?. Is it worthwhile to include these changes into BL?

**Comment by fpgamcu** [comment]
Changing parameters from defines to context parameters may not be ported into bootloader, if there is no need to share this parameters (static IP config or DHCP) with bootloader.
Using reset pin to reset WIFI would be good to be ported to the BL.

**Comment by ralcaide** [comment]
TODO RAE: To manage task development in BL

**Comment by soporteHW** [comment]
Failed test:
![image](https://user-images.githubusercontent.com/28917446/56670481-353ed480-66b3-11e9-8718-19e3d9d4cd87.png)

After 36 minutes, the wifi does not appear

Point: The USR is restarted very frequently (each 30 secs?)

Test ok: https://sinapseenergia.testrail.io/index.php?/tests/view/1634&group_by=cases:section_id&group_order=asc&group_id=170
