### ISSUE TITLE
[S2-LP][HW] To connect expansion board to EasyNet 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#187]
To connect https://www.st.com/en/ecosystems/x-nucleo-s2868a1.html to the current EasyNet in order to have a 6LoWPAN transceiver for Southbound communication

**Comment by sinapseenergia** [comment]
![connection_xnucleo_easynet2p0](https://user-images.githubusercontent.com/27274287/50006255-6d1f6800-ffad-11e8-9470-48c687241eaf.jpg)

This image shows the connection between X-NUCLEO-S2868A1 board and one EasyNetV2p0 EN_SA_v2p0 board.

**Comment by sinapseenergia** [comment]
After connecting the SPI interface, it is needed to enable power with PD3 or ONOFF_Peripheral_1 signal. One generic GPIO is used also for ruling the shutdown in S2-LP.

**Comment by vAnArhist** [comment]
From ST Middleware pins GPIO0-GPIO3 is using also for interrupts for MCU in order to notify it about various events. Pin PC7 is used also (see https://www.st.com/content/ccc/resource/technical/layouts_and_diagrams/schematic_pack/group0/2c/a2/0f/06/b6/54/42/de/X-NUCLEO-S2868A1_SCHEMATIC/files/x-nucleo-s2868a1_schematic.pdf/jcr:content/translations/en.x-nucleo-s2868a1_schematic.pdf)

**Comment by ralcaide** [comment]
I understand from your comment that several more connections different to the proposed ones should be done, isn't?. 
@vAnArhist , please clarify here, after your analysis, what connections exactly should be done between AP and ST board

**Comment by vAnArhist** [comment]
PE6 - GPIO0,
PE7- GPIO1,
PE8 - GPIO2,
PE9 - GPIO3.
Other pin connections is ok.

**Comment by ralcaide** [comment]
Last image differs from your previous comment, In the image I only see:

PE9 - GPIO0

Is that right?

**Comment by fpgamcu** [comment]
yes, used code from node it is possible to limit connection only to GPIO0 instead of all 4 GPIOs

**Comment by ralcaide** [comment]
Tested OK

**Comment by ralcaide** [comment]
In the new version of the HW (V3p0) we are using PE6 instead PE9. 

Attached image of the V3p0 design.
![image (25)](https://user-images.githubusercontent.com/2856585/59581976-fb98b180-90d6-11e9-9602-8c604b7e1f29.png)

@fpgamcu , could you please modify the FW in order to change this configuration and allow us testing the new devices?

**Comment by ralcaide** [comment]
V2p0 : Works OK
V3p0: It does not work

**Comment by ralcaide** [comment]
thanks, we will test and provide feedback
