### ISSUE TITLE
[RF][Mismatching] To understand how is working now the RF TX - RX and improve matching with End Devices

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#192]
We have now three kind of End Nodes and not all of them are answering to the AP. However, they are answering to a legacy transparent modem.

| Gateway | EC Legacy | EC-NEMA | EC-RF |
|-------------|---------------|---------------|------------|
| Legacy  | OK | OK  | OK |
| AP | OK | KO | KO |

Normally, the new ECs execute the actions but they are not answering/sending the expected RF Frame.

We observed also that EC Legacy answers much more faster when the query comes from Legacy gateway (300ms) that from the query comes from AP (1000ms). This fact possible means that AP is sending a query much slow than Legacy Gateway. The TDA is normally automatically adapted to reception speed.

Next actions are required:
 
- Explanation about the RF sending speed from AP (All elements involved). We require a table or chart with every time involved (MCU -> SPI -> TDA -> Air, delays, etc) in order to have a clear and global view about what is happening. Other developers will do same for EC and EC-NEMA after the table for AP is done
- How to increase the global sending speed?  
- Study mismatching and adapt speed in order to work well in every case

# Test results

| Device | ID | MCU Freq | RX Time | Distance|
|----|----|----|----| ---|
|EC-LC-NEMA | 530001 | 26Mhz | 0 | 12m |
|EC-LC-NEMA | 530002 | 26Mhz | 0 | 12m |
|EC-LC-NEMA | 530003 | 8Mhz | 0 | 12m |
|EC-LC-NEMA | 530004 | 8Mhz | 0 | 12m |
|EC Evo - Legacy | 514853 | ?  | Default / 0 | 3m |
|EC Evo - Legacy | 523751 | ? | Default / 0 | 12m |

| Device / GW | Test | 530001 |  530002 | 530003 | 530004 | 514853 | 523751 |
| --- | --- | --- |  ---  | --- |  ---  | --- | --- |
| AP | PING | NO ACK |  NO ACK  | 800ms + T |  800ms + T  | 1000ms + T / NO ACK | 1000ms + T/ NO ACK  |
| TM (Legacy) | PING | 300ms |  300ms  | 1000ms |  1000ms  | 1200ms / 300ms | 1200ms / 300ms  |
| AP | Metering | NO ACK |  NO ACK  | NO ACK |  NO ACK  | 1300ms + T / 400ms + T | 2000ms + T / 1000ms + T |
| TM (Legacy) | Metering | 300ms |  300ms  | 300ms |  300ms  | 600ms / 600ms | 1200ms / 1200ms  |

T is an unknown time from AP to TM. It can be calculated but suppose is bigger than 700ms (normally around 1 second). So AP is slower than TM

Here the original file with test results. The tables are the resume

[RF_TEST.pdf](https://github.com/Sinapse-Energia/AP-Sinapse/files/2702677/RF_TEST.pdf)

**Comment by ralcaide** [comment]
@fpgamcu , could you please take a look to this task with very high priority, please?. We need at least an answer to the first two points asap. 
We will send you also all the devices in order to characterize in the best possible way what is happening but now we need at least increase the sending speed in order to perform empirical tests

**Comment by ralcaide** [comment]
Additional questions:
1. How much time needs the function sendData (RF_Transceiver.c line 2071) for one PING frame?
2. How much time needs the function TDA5340_start_TX_FIFO (RF_Transceiver line 1660) for one PING frame?

**Comment by ralcaide** [comment]
3. The function SPI_sendByte (RF_Transceiver.c line 1879) used HAL_SPI with 1000 as a timeout, in other versions of this driver uses 100 as a timeout. Could this fact provokes slower speed?

**Comment by ralcaide** [comment]
Attached results file (resume in the description tables)

[RF_TEST.pdf](https://github.com/Sinapse-Energia/AP-Sinapse/files/2702675/RF_TEST.pdf)

**Comment by fpgamcu** [comment]
3. In SPI_sendByte those 1000 timeout is only for compatibility with HAL calls. Whenever you use 1000 or 100 ticks it still will send data by SPI with SPI clock speed (652343 bit per second with current settings, prescaler 64, sys clock 167 MHz, bus clock 41.75 MHz)

**Comment by fpgamcu** [comment]
1 and 2 - I am measuring now the time

**Comment by fpgamcu** [comment]
1. Time spent on sendData (RF_Transceiver.c line 2071) is 146 msec
2. Time spent on TDA5340_start_TX_FIFO (RF_Transceiver line 1660) 131 msec

**Comment by ralcaide** [comment]
a. So, 131 msec for 11 bytes (ping) means around 12 msec per byte, right? 
b. We suppose that TDA send the bytes at the same speed, is that right? or depends of something else?
c. Could we increase this speed?

**Comment by ralcaide** [comment]
The code used by the end nodes not answering well to the AP is here:

https://github.com/Sinapse-Energia/EC-LC-NEMA/tree/fixstability

**Comment by ralcaide** [comment]
I've created a file in order understand how is working each device. @fpgamcu , please fill the AP row and try to fill the other rows looking at the code of the other devices.

Here is the file https://docs.google.com/spreadsheets/d/1mUV6gDzYZ3d6Nbbc7lMgAZmTN7cqS2aGVIz_Ns6I4Cs/edit?usp=sharing

**Comment by fpgamcu** [comment]
Status update:
Debugged with latest AP code and EC-LC-NEMA
Reproduced the issue: packets sending from AP to Node, Node receives packet, AP not receiving packets from node
Now checking RF transfer with analyzer, checking with debugged Node sending, checking with debugger AP receiving anything/broken packets

**Comment by soporteHW** [comment]
Results from last test performed included in the following table:

![image](https://user-images.githubusercontent.com/28917446/51463141-c32cbb80-1d62-11e9-91ae-c1a0daa3e0f9.png)

**Comment by ralcaide** [comment]
To be tested after the command 220; is done
