### ISSUE TITLE
[6LoWPAN][M95] GPRS connection is not working

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#196]
We've tested with two kind of APs:

- ETH: Is working OK
- GPRS: It does not work. KO.

It is necessary to fixt it.

**Comment by ralcaide** [comment]
@fpgamcu , please provide feedback and estimation. Any idea? By default it should works, isn't?

**Comment by fpgamcu** [comment]
I will check GPRS. Previously checked on my side only with ETH.

**Comment by ralcaide** [comment]
@fpgamcu , could you please do that dynamically depending if it is GPRS or not?
IF ETH: MAX_TABLE_SIZE = 600 and MAX_SUBSPACES = 5
IF GPRS: MAX_TABLE_SIZE = 300 and MAX_SUBSPACES = 2

**Comment by fpgamcu** [comment]
Sure, should not take a lot of time, 2 hours should be enough with testing
