### ISSUE TITLE
[CMC][Relay][19.8.0] 5/7 relays are activated when the device is new

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#198]
Version 19.8.0 is activating 5 relays always in a new device and formatted SD. Tested also without connectivity.

**Comment by ralcaide** [comment]
@fpgamcu , any idea about that? Could you provide feedback? Current version is not usable

**Comment by fpgamcu** [comment]
I will check and fix

**Comment by ralcaide** [comment]
Reproduced and will fix it

**Comment by ralcaide** [comment]
To be tested also using FW VERSION strings bigger than 8 bytes

**Comment by soporteHW** [comment]
Tested OK

Relay1: https://sinapseenergia.testrail.io/index.php?/tests/view/1578&group_by=cases:section_id&group_order=asc&group_id=130

Relay 2-7: https://sinapseenergia.testrail.io/index.php?/tests/view/1613&group_by=cases:section_id&group_order=asc&group_id=130
