### ISSUE TITLE
[Design] To define the Context

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#2]
To define the Context:

- Variables (What?)
- Types (Strings, int, arrays, structures...)
- Attributes (Persistent, RF, MQTT...)

**Comment by sinapseenergia** [comment]
This information will be available online until V1p0
Can be accesible here (**Not Validated**)

https://paper.dropbox.com/doc/AP-Context-fje5zWhk0fHoS1AVXCEsw

**Comment by ralcaide** [comment]
@francisjjp please, could you calculate the size of the different parts of the Context?. Please provide a size for:

- Level 0 hierarchy vars
- Level 1 hierarchy vars. This is an EPD

**Comment by francisjjp** [comment]
First SIZE-ASSIGMENT draft.

1.  Device_API_Version. (8 bytes if string-ascii coded, it could be fewer).
2. Bootloader_Uri. (50 bytes if string-ascii coded).
3. Bootloader_User. (15 bytes if string-ascii coded).
4. Bootloader_Pass. (15 bytes if string-ascii coded).
5. APN_Name. (50 bytes if string-ascii coded).
6. APN_User. (15 bytes if string-ascii coded).
7. APN_Pass. (15 bytes if string-ascii coded).
8. Main_MQTT_Server_Name. (50 bytes if string-ascii coded).
9. Main_MQTT_Server_User. (15 bytes if string-ascii coded).
10.  Main_MQTT_Server_Pass. (15 bytes if string-ascii coded).
11. Backup_MQTT_Server_Name. (50 bytes if string-ascii coded).
12. Backup_MQTT_Server_User. (15 bytes if string-ascii coded).
13.  Backup_MQTT_Server_Pass. (15 bytes if string-ascii coded).
14. MQTT_Client_ID. (20 bytes if string-ascii coded).
15. MQTT_Tpico_Root. (20 bytes if string-ascii coded).
16. Device_OnDemand_Publication_Topic. (20 bytes if string-ascii coded).
17. Device_OnPeriodic_Publication_Topic.(20 bytes if string-ascii coded).
18. Device_Alert_Publication_Topic. (20 bytes if string-ascii coded).
19. EPD_OnDemand_Publication_Topic. (20 bytes if string-ascii coded).
20. EPD_OnPeriodic_Publication_Topic. (20 bytes if string-ascii coded).
21. EPD_Alert_Publication_Topic. (20 bytes if string-ascii coded).
22. EPD_Time_Granularity. 4 bytes .
23. Device_ID. char[6] 6 bytes. (But if it is only for saving 6 digit-hex, it can be coded in 3 bytes).
24. Device_Grupo_ID. char[6] 6 bytes.
25.  Global_Device_Relays_Output_Status_Byte. 16 bytes. (It codes 128 bits = 128 maximum PINS).
26. Global_Device_GPIO_Status_Bytes. 16 bytes (=128 bits).
27. Device_Digital_Output_1_Value, ...Device_Digital_Output_N_Value. 16 bytes for all (=128 bits).
28. Device_EPD_List. 4 bytes. (For saving only initial EPD address start).
29. Device_Status_at_Start. 16 bytes (=128 bits).
30. Device_Last_Known_Start. 16 bytes (=128 bits).

--------------------

31. EPD_ID. 3 bytes (6 digit-hex).
32. EPD_API_Version. 2 bytes.
33. EPD_Group_ID. 2 bytes.
34. EPD_Publication_Topic. 40 bytes.
35. EPD_Subscription_Topic. 40 bytes.
36. EPD_Temperature. 1 byte.
37. EPD_Temperature_Threshold. 1 byte.
38. EPD_Temperatyre_Timestamp. 4 bytes.
39. EPD_Current. 2 bytes.
40. EPD_Current_Threshold. 2 bytes.
41. EPD_Current_Timestamp. 4 bytes.
42. EPD_Voltage. 2 bytes.
43. EPD_Voltage_Threshold. 2 bytes.
44. EPD_Voltage_Timestamp. 4 bytes.
45. EPD_Power. 2 bytes.
46. EPD_Power_Threshold. 2 bytes.
47. EPD_Power_Timestamp. 4 bytes.
48. EPD_Dimming_Status. 1 byte.
49. EPD_Power_Status. 1 byte.
50. EPD_Power_Factor. 1 byte.
51. EPD_Power_Factor_Threshold. 1 byte.
52. EPD_Power_Factor_Timestamp. 4 bytes.
53. EPD_Frequency. 1 byte.
54. EPD_Frequency_Timestamp. 4 bytes.
55. EPD_Global_Digital_Status. 16 bytes.
56. EPD_Device_Status. 1 byte.
57. EPD_RF_Flags_Byte. 1 byte.
58. EPD_RF_Success_Ratio. 1 byte.
59. EPD_RF_Hops. 1 byte.
60. EPD_RF_Rtime. 2 bytes.
63. EPD_RF_Redundancy. 1 byte.
64. EPD_TTL. 1 byte.
65. EPD_Load_Nominal_Power. 2 bytes.
66. EPD_Safe_Mode. 16 bytes.
67. EPD_Internal_Flags. 1 byte.

**Comment by francisjjp** [comment]
Size take consideration from point 1-30:  588 bytes.

Size per EPD. from point 31-65:  173 bytes.

**Comment by ralcaide** [comment]
The context variables should be saved in the last sector (128 KBs). How many EPDs?

128000 - 600 (Supossing that first level vars need 600 bytes) = 127400
127400 / 200 (Supossing that an epd needs 200 bytes) = 637 EPDs

These numbers are normally good for us.

For security, maybe should be use the last two sectors??. What do you think @sinapseenergia and @francisjjp
