### ISSUE TITLE
[CMC - Metering][EASTRON]  To display imported energy instead exported

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#203]
The L3_READ_METERING_* commands are displaying the exported energies instead the imported. 

[EASTRON]: Please change that in order to display the imported energies
[CIRCUTOR]: To verify what energy is got, it is necessary also to display the imported energy.

Example of diff is attached

[this_diff_-_.c.txt](https://github.com/Sinapse-Energia/AP-Sinapse/files/2971272/this_diff_-_.c.txt)

**Comment by fpgamcu** [comment]
Estimation is 2 hours, 
Have you external PC with circutor analyzer connected?

**Comment by ralcaide** [comment]
Not at this moment. We will do that and I will let you know.
We tested in Eastron and in this case is necessary to change the Exported for Imported.

**Comment by soporteHW** [comment]
Tested: https://sinapseenergia.testrail.io/index.php?/tests/view/1629&group_by=cases:section_id&group_order=asc&group_id=170

OK

![image](https://user-images.githubusercontent.com/28917446/56595494-0bbc7500-65ef-11e9-86d1-0a92c8fc4680.png)

**Comment by ralcaide** [comment]
Great, we should test also with a the Circutor analyzer in order to check of we are using the correct energy or not. 
@soporteHW , could you do that, please?
