### ISSUE TITLE
[609;] To add new field to 609; : BINARY_INFO

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#206]
To add hardcoded info to the binary file, this info should be recovered with 209;. The goal is to have info about the binary installed.

[609;](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#retrieve-fw-version-result)

**Comment by soporteHW** [comment]
Tested ok.
https://sinapseenergia.testrail.io/index.php?/tests/view/1619&group_by=cases:section_id&group_order=asc&group_id=170
