### ISSUE TITLE
[CMC Context][BUG] CMC context is not working

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#213]
The context CMC in version 19.12.01 is NOT working. It is not able to connect in GPRS nor in ETH nor in WIFI.

The contexts AP and EN are working OK with all the connection options.

**Comment by ralcaide** [comment]
Make:

`# CMC
TOPIC=CMC_GENERIC
CONTEXT='CMC'
################################################
#CMC GPRS
INFO='CMC_GENERIC_GPRS'
CONNECTION='GPRS'

make clean
make change_cmc
make change_gprs
make config_gprs APN=$APN USR= PASSWD=
make config_mqtt_broker MQTTURI=soporte-tecnico.bitnamiapp.com MQTTPORT=1883 MQTTUSER= MQTTPASS=
make config_mqtt_topic MQTTTOPIC=$TOPIC
make config_version FWVER=$VERSION
make config_info BINFO=$INFO  
make all

cp $ORIG_BIN $DEST_PATH$DEST_BIN
CRC=$(crc32 $DEST_PATH$DEST_BIN)
echo CRC32 is $CRC
perl -e 'print pack "H*", "'$CRC'"' >> $DEST_PATH$DEST_BIN

mv $DEST_PATH$DEST_BIN $DEST_PATH$VERSION'/CL-'$CONTEXT'-'$TOPIC'-'$CONNECTION'-'$APN'-'$VERSION'.bin'`

**Comment by ralcaide** [comment]
@fpgamcu , are you able to reproduce this problem? We need to to have a CMC context working

**Comment by fpgamcu** [comment]
I will check it today

**Comment by ralcaide** [comment]
@fpgamcu , have you checked the context CMC is working in last version (19.26.00)?

**Comment by fpgamcu** [comment]
I will test and if needed fix it today

**Comment by fpgamcu** [comment]
Tested on my device - latest commit is fixing issue. Now all contexts should work ok.

**Comment by ralcaide** [comment]
Tested OK in 19.26.03
