### ISSUE TITLE
[AP][ALL] Integrate 6LP features into the main branch

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#218]
Now, we have two parallel branches and we miss several important features in each one.
It is necessary to integrate the 6LP RF as a communication southbound in the main branch in order to have all the developed features for CMC, EN and AP accessible

**Comment by fpgamcu** [comment]
By now Makefile compilation is not working for merged code, I'll fix it tonight

**Comment by ralcaide** [comment]
Thanks. 
I see only two possible RFs in Definitions.h. Is that right or should be three (TDA have two differents modes)?
We wait to to makefile

**Comment by fpgamcu** [comment]
Old/New RF driver mode is switched in runtime through commands,
RF/6LP mode is switched through define, USE_6LP_TRANSCEIVER enable or disable 6LP instead of RF
It is also possible to have 6LP switch in runtime, but as I checked, we have not enough RAM in order to use this feature.

**Comment by ralcaide** [comment]
Thank you, everything is clear. By the moment it is OK for us like that

**Comment by ralcaide** [comment]
Estimated time for the makefile?

**Comment by fpgamcu** [comment]
Makefile operation was changed in latest commit, now all parameters is set directly through compiler defines.
Please use ‘make help’ in build folder for details and example.

**Comment by ralcaide** [comment]
Thanks, we will test it asap.
Question: What BL should we use? Should we use a different BL depending the context or the M4_EN1.1_F427VG_V19.24.00 will work for every board?

**Comment by ralcaide** [comment]
@fpgamcu , could you please answer my previous question? What BLs should be use depending the HW?

**Comment by fpgamcu** [comment]
You can use BL V19.24.00

**Comment by ralcaide** [comment]
Tested OK in 19.26.01
