### ISSUE TITLE
[CMC][Metering] L3_READ_METERING_P is not working

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#219]
The command L3_READ_METERING_P is not working at all in 19.12.01. To fix it

**Comment by ralcaide** [comment]
@fpgamcu , have you tested this command is working properly in the last version 19.26.00 ?

**Comment by fpgamcu** [comment]
I will test and if needed fix it today

**Comment by ralcaide** [comment]
@fpgamcu , how is going this task? Is it fixed with last commit too?

**Comment by fpgamcu** [comment]
I will be able to test with analyzer at 19:00 because Analyzer is now in other office, Roman has used it.

**Comment by fpgamcu** [comment]
Here is one issue. I noticed that for ANL subspace and for EPD subspace context call GenericReadElement and GenericWriteElement with the same index for different subspaces. It will lead to erasing EPD data with ANL data and vice versa. I will study this behavior more, but for now CMC and AP context is not compatible.

**Comment by ralcaide** [comment]
ok, by the moment we will use only the context EN and CMC. It is to say, we will not sue context AP. We will test the context CMC and create a new task to review the found problem

**Comment by ralcaide** [comment]
Tested OK in 19.26.03
