### ISSUE TITLE
[API 313 - 713] The command 713; is not well formed

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#26]
This command includes two ";" at the end. It should include only one.

Related with: #15

**Comment by fpgamcu** [comment]
I noticed it too. Seems context bug. I will investigate and fix.

**Comment by ralcaide** [comment]
I think it is related with the metadata, with the definition of the command. Maybe there is an extra ";"

**Comment by fpgamcu** [comment]
`TEXT3%713;@EPD($EPD::EPD,$EPD::P)%List of EPDs and power values%%` no, there is no `;` at the end of command

**Comment by ralcaide** [comment]
TESTED OK
