### ISSUE TITLE
[API 316] The command 316 is returning an empty answer

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#27]
It seems that the command 316; is returning an empty answer in the publication topic related with the AP (At this moment LU/LUM/SEN). 
The command 316; should not return anything

Related with #14

**Comment by fpgamcu** [comment]
Seems compiler bug.
We have `char* out;`
And the next check `if (out) {` that gives true even if `out = NULL`
Even `if (out != NULL) {` gives true too.
Will try to fix now

**Comment by fpgamcu** [comment]
Only the next line is working `if ((uint32_t)out != 0) {`

**Comment by ralcaide** [comment]
TESTED OK

Closing the issue
