### ISSUE TITLE
 [Integration] To integrate the NB and API Engine of EC-M2M

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#3]
The Northbound MQTT and the API Engine has been designed and developed in the project EC-M2M. It is necessary to integrate it in the AP. Taking into account:

- The Received Frames are different
- The commands make something different. For example, the 3; send a RF frame instead act over a relay. By the moment it is necessary to modify this commands in order to publish a trace "Executing command X" but avoiding any kind of actuation

**Comment by francisjjp** [comment]
Uploaded basic project into Integration--M2M branch but with compilling errors (commit: dbde7d0c3fb5f848f7c8f9b0b3e8b08231ed10bd).

**Comment by francisjjp** [comment]
Errors are following:

` 19:09:48 **** Rebuild of configuration Debug for project AP-Sinapse ****
Info: Internal Builder is used for build
arm-atollic-eabi-gcc -c ..\Src\stm32f4xx_hal_msp.c -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=gnu11 -DSTM32F4XX -DSTM32F40XX -DUSE_HAL_DRIVER -I../src -IC:\Users\Francis\git\AP-Sinapse\Inc -IC:\Users\Francis\git\AP-Sinapse\Libraries\MQTTPacket-Paho -IC:\Users\Francis\git\AP-Sinapse\Drivers\CMSIS\Device\ST\STM32F4xx\Include -IC:\Users\Francis\git\AP-Sinapse\Drivers\CMSIS\Include -IC:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc -IC:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc\Legacy -O0 -ffunction-sections -fdata-sections -g -fstack-usage -Wall -o Src\stm32f4xx_hal_msp.o 
arm-atollic-eabi-gcc -c ..\Drivers\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cortex.c -mthumb -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=gnu11 -DSTM32F4XX -DSTM32F40XX -DUSE_HAL_DRIVER -I../src -IC:\Users\Francis\git\AP-Sinapse\Inc -IC:\Users\Francis\git\AP-Sinapse\Libraries\MQTTPacket-Paho -IC:\Users\Francis\git\AP-Sinapse\Drivers\CMSIS\Device\ST\STM32F4xx\Include -IC:\Users\Francis\git\AP-Sinapse\Drivers\CMSIS\Include -IC:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc -IC:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc\Legacy -O0 -ffunction-sections -fdata-sections -g -fstack-usage -Wall -o Drivers\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cortex.o 
In file included from ..\Drivers\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cortex.c:101:0:
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:194:1: error: unknown type name 'HAL_StatusTypeDef'
 HAL_StatusTypeDef HAL_Init(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:195:1: error: unknown type name 'HAL_StatusTypeDef'
 HAL_StatusTypeDef HAL_DeInit(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:198:1: error: unknown type name 'HAL_StatusTypeDef'
 HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:198:33: error: unknown type name 'uint32_t'
 HAL_StatusTypeDef HAL_InitTick (uint32_t TickPriority);
                                 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:208:16: error: unknown type name '__IO'
 void HAL_Delay(__IO uint32_t Delay);
                ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:209:1: error: unknown type name 'uint32_t'
 uint32_t HAL_GetTick(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:212:1: error: unknown type name 'uint32_t'
 uint32_t HAL_GetHalVersion(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:213:1: error: unknown type name 'uint32_t'
 uint32_t HAL_GetREVID(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:214:1: error: unknown type name 'uint32_t'
 uint32_t HAL_GetDEVID(void);
 ^
C:\Users\Francis\git\AP-Sinapse\Drivers\STM32F4xx_HAL_Driver\Inc/stm32f4xx_hal.h:223:17: error: unknown type name 'uint32_t'
 void HAL_GetUID(uint32_t *UID);
                 ^

19:09:49 Build Finished (took 880ms) `

**Comment by francisjjp** [comment]
All branch has been erased and process has been repeated.

**Comment by francisjjp** [comment]
[TESTING 4 hours] HF problems refered to IRQ in TIM6 and TIM7.

**Comment by francisjjp** [comment]
[TESTING TIMERS 1hour]. Resolved HF. The .s file was one file from F0 family, it is correct and it will be included in github.

**Comment by francisjjp** [comment]
It seems there is something strange with atollic configuration and HF. With Cocoox and same hardware that using in atollic, HF never happens, but with atollic, the HP happens too many times.

**Comment by francisjjp** [comment]
[REQUEST INFORMATION 0.5hour]. One mail has been sent to provider in order to know if there is some recommended configuration into Atollic to develop firmware.

**Comment by ralcaide** [comment]
@francisjjp have you read all the info available in our Wiki and in the Atollic resources?

http://sinapse.bitnamiapp.com/redmine/projects/firmware-global/wiki#Atollic-installation-and-configuration

**Comment by francisjjp** [comment]
[AP-Sinapse_basic_STM32CubeMx_embedded_Atollic.tar.gz](https://github.com/Sinapse-Energia/AP-Sinapse/files/1182943/AP-Sinapse_basic_STM32CubeMx_embedded_Atollic.tar.gz)

[GENERATING BASIC CODE. 3hours] It is uploaded basic code for AP-Sinapse generated by STM32CubeMX embedded in own Atollic. It is need to put code yet (JRB Code, MQTT from Paho,...)

**Comment by francisjjp** [comment]
[INTEGRATED & TESTED. 3 hours]. Finally one basic-working AP firmware has been uploaded. HF have disappeared. The proccess was to generate basic cproject using STM32CubeMX embedded in own Atollic True Studio. The the code from EC-M2M was migrated to F4 family from F0 family.

**Comment by francisjjp** [comment]
There is one only warning in this project:

`.\Src\M95lite.c: In function 'M95_Connect':
..\Src\M95lite.c:1302:31: warning: pointer targets in passing argument 2 of 'Lookup' differ in signedness [-Wpointer-sign]
   if ((j = Lookup(DataBuffer, (char *)answerQNTP)) > 0) {
                               ^
In file included from ..\Src\M95lite.c:12:0:
../Inc/circular.h:62:12: note: expected 'uint8_t * {aka unsigned char *}' but argument is of type 'char *'
 extern int Lookup (st_CB *, uint8_t *);`

**Comment by francisjjp** [comment]
Regarding the position of saving data into FLASH in own microcontroller STM32F405xx, the actual address is 0x80E0000 , this is sector 11 and it takes 128kb.

It can be changed. It is needed to do standard the position of saving local data for all projects and if it is possible for different microcontroller families (STM32F030CC and STM32F405VG)

STM32F405xx microcontrollers have following flash distribution and sector sizes.

Sector 0  ->Address: 0x0800 0000 - 0x0800 3FFF. Size : 16 Kbytes
Sector 1  ->Address 0x0800 4000 - 0x0800 7FFF . Size: 16 Kbytes
Sector 2  ->Address 0x0800 8000 - 0x0800 BFFF.  Size: 16 Kbytes
Sector 3  ->Address 0x0800 C000 - 0x0800 FFFF. Size:  16 Kbytes
Sector 4  ->Address 0x0801 0000 - 0x0801 FFFF. Size:  64 Kbytes
Sector 5  ->Address 0x0802 0000 - 0x0803 FFFF. Size: 128 Kbytes
Sector 6  ->Address 0x0804 0000 - 0x0805 FFFF. Size: 128 Kbytes
Sector 7  ->Address 0x0806 0000 - 0x0807 FFFF. Size: 128 Kbytes
Sector 8  ->Address 0x0808 0000 - 0x0809 FFFF. Size: 128 Kbytes
Sector 9 - >Address 0x080A 0000 - 0x080B FFFF. Size: 128 Kbytes
Sector 10->Address 0x080C 0000 - 0x080D FFFF. Size: 128 Kbytes
Sector 11->Address 0x080E 0000 - 0x080F FFFF .Size: 128 Kbytes

If bootloader is used. The bootloader takes first sectors (Sector 0 and Sector 1). Application program and backup program takes consecutive sector. For this reason last sector is taken for saving specific application data. Sharing variables data are saved in own associated sector into Application program).
