### ISSUE TITLE
[HW - EEPROM] Check schematics 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#64]
We are getting problems with the EEPROM, after a random time we get I2C busy. Please, check the schematics if everything looks fine
[Schematics](https://github.com/Sinapse-Energia/AP-Sinapse/tree/master/Doc/schematics)

Please, be aware: 

-The resistors used are 4k7 instead of 2k2
-Elements into antenna stage regarding TDA5340 device does not match with asseblied PCB. (Schematics are indicated for 912MHz, assemblied PCB is for 433.92MHz).
- The EEPROM appearing in the Schematics is WRONG. We use a ST EEPROM with the following data:

Ref: M24M02-DRMN
1) We put pin 1,2,4 to ground.
2) Pin A2 is pull-up to 3.3V with one 10k resistor.
3) VCC is 3.3V
4) /WC is tied to GPIO line microcontroller
5) SCL and SDA is i2c bus and they have the pull-up resistor for working bus.

Here is possible to see the description of the problem: 
[Sinapse EEPROM Problem](https://community.st.com/message/172945-problem-communication-stm32f405vg-and-i2c-eeprom-m24m02-drmn)

**Comment by fpgamcu** [comment]
Strange thing. On schematic SCL and SDA resistors have 2.2k and on my board 4.7k

**Comment by ralcaide** [comment]
Yes, true, this a mistake in the schematic. The resistors are 4.7k. Anyway, this difference should not affect.

**Comment by ralcaide** [comment]
We've received feedback from ST engineer. He is asking about the write / read operations, are we waiting to end of the write operation to read and viceverse?. @fpgamcu, please, verify me this point.

Also, he recommend us to put the WP pin to GND in order to avoid problems. It is an Atmel recommendation.

**Comment by ralcaide** [comment]
Closing the issue

redesign done and SD is now also available
