### ISSUE TITLE
[ML 8 - CMC - 4;] To develop the command 4; in order to public the status periodically

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#67]
See [Status periodically](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#ask-about-status-periodically)

**Comment by ralcaide** [comment]
@fpgamcu , question:

What happens if the EN receives: `4;30;22:00;06:00;-1`, will publish the status between 22:00 and 06:00 even if the hours are related to different days?

**Comment by fpgamcu** [comment]
In current version it will never publish. Now condition of publish is next (nowAbsMinute >= startAbsMinute && nowAbsMinute <= endAbsMinute).
But it is possible to modify in order to publish between 22:00 and 06:00, if necessary.

**Comment by ralcaide** [comment]
Thanks, an improvement is planned for next sprints. See #125

**Comment by ralcaide** [comment]
Tested on T224

**Comment by ralcaide** [comment]
To be tested through C9

**Comment by ralcaide** [comment]
V1.18: Tested again with T224
