### ISSUE TITLE
[ML 8 - CMC - 10;] To develop actuation over relays periodically

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#69]
See [act over relays periodically](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#act-over-relays-periodic--scheduled)

Previous needed tasks:
- Set GPS : #92  
- Calculate automatically Sunset / Sunrise, read sunset / sunrise: #93

**Comment by ralcaide** [comment]
TODO by RAE: To divide in smaller subtasks

**Comment by ralcaide** [comment]
To be tested through C2

**Comment by ralcaide** [comment]
After #141, all the relays are working ok under periodic actuations except the relay 7. @fpgamcu, please fix it

**Comment by ralcaide** [comment]
@fpgamcu , please provide a time estimation.

**Comment by fpgamcu** [comment]
Estimate is 2 hours max.

**Comment by ralcaide** [comment]
Tested OK. T460.

OK with fix hours, KO with SS / SR. To me managed in other issue : #144
