### ISSUE TITLE
[BUG]. Behaviour not correct with 313; response.

### ISSUE THREAD

**Issue by francisjjp** [Sinapse-Energia/AP-Sinapse#75]
It has been found one bug regarding 713 response. When different EPD are registered in different AP devices  (same broker and same channel). After one **313**; request to **AP_x** .

 **The response is 713;EPD_a;EPD_b;...;EPD_n.** 

**The right answer is: 713;AP_x;EPD_a;EPD_b;...EPD_n;**

**Comment by ralcaide** [comment]
TESTED OK
