### ISSUE TITLE
[ML 9] To use hard SPI instead soft SPI with RF transceiver

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#78]
In the new HW it is possible to use the hard SPI communication with the RF transceiver. Use it instead the soft SPI

NOTE: in this PCB, TDA Infineon interface use native SPI2 interface. It's mandatory to initialize this interface in "spi.c" file and remove GPIO pins declaration (i_NCS, i_SDK, I_SDI, i_SDO).

**Comment by ralcaide** [comment]
@fpgamcu , this issue will be finished in the current sprint? Today? If not we move it to next sprint

**Comment by fpgamcu** [comment]
Will be finished today.

**Comment by ralcaide** [comment]
@fpgamcu , what is the status of this task? Normally should be finished in the previous Sprint W4 but I think is not. I don't see any commit related with and also the results of the testing are very poor.

Could you provide me please feedback?

**Comment by fpgamcu** [comment]
Sorry, There was some error in my local git repo. It displays me that all changes are pushed, but there is no changes on server. Now all pushed.

**Comment by ralcaide** [comment]
Ok, thanks.
@fpgamcu , have you tested the RF with this new version? Should I see improvements or not yet?
The queue management algorithms have not been change, isn't? Was Alexander working on that several weeks ago, right?

**Comment by fpgamcu** [comment]
We have found several issues in new queue implementation, that need to be fixed. In several hours Alex should finish testing of #69 and #92. After this he will be able to finish with queue management.

**Comment by ralcaide** [comment]
OK, but I have some comments:

- Linked to what issue is done these queue improvement management?
- This bug fixing was not planned for the current Sprint but if Alex has time to do that after finish the planned work will be great. Please provide me the issue where is he working in order to insert it into the Sprint or to create a new one if it is needed.

**Comment by fpgamcu** [comment]
I think we need new issue, something like "Improve RF communication to reduce amount of skipped incoming packets".

**Comment by ralcaide** [comment]
Ok, here is the issue: #94 

Could I include it in the current Sprint?

**Comment by fpgamcu** [comment]
Yes

**Comment by ralcaide** [comment]
Tested OK
