### ISSUE TITLE
[EN V1.1 - LED] To improve the led behaviour in order to clarify where is the program  

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#90]
The board has for LEDs but we are using only one with the next behaviour:

- If the board has power and the SD is working : Led ON
- If the board has power and the SD is not working: Led Blinking

This behaviour is not very useful. Develop the following:

- Led 1 (X6) : Manages status of bootloader and client app. OFF and the beginning, then blinking during bootloader working, when bootloader finish, Led 2 is turned ON and Led 1 continues blinking until the connection of the client app with the broker is performed
- Led 2 (X7): Manages status of NVM. OFF during bootloader. ON in Client app when the NVM is working right. Blinking in Client app when NVM is not working right

LED 1 | LED 2 | Status
------------ | ------------- | ---------------
OFF | OFF | OFF
Blinking | OFF | Bootloader
Blinking | ON | Client APP - Not connected - NVM OK
ON | ON | Client APP - Connected - NVM OK
ON | Blinking | Client APP - Connected - NVM KO
Blinking | Blinking | Client APP - Not Connected - NVM KO

**Comment by ralcaide** [comment]
The AP part is done. To implement the Bootloader part but in its project

**Comment by sinapseenergia** [comment]
Looks like there is a BUG in LED expected behaviour.
Under NVM fault, device publish into DEBUG channel this problem, but in the tested case both LEDs remains ON
Please, check/clarify if in all cases which implies publish NVM fault in DEBUG channel, LED2 behaviour is changed to "Blinking"

**Comment by ralcaide** [comment]
The previous behaviour was detected with EEPROM as a NVM

**Comment by ralcaide** [comment]
Closing the issue because we will set only a RGB Led. It will be created a new issue to manage the behaviour of this Led.
