### ISSUE TITLE
[Compile for F427VG] Create needed files for compile the code for this MCU 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#91]
We are testing a F405VG compatible MCU with more RAM, named F427VG.
We understand that the code should be directly compatible and the only difference should be the files where the RAM is defined, .ld and stm32f427xx.h

Create / Modify the needed files in order to compile for this MCU

**Comment by ralcaide** [comment]
@fpgamcu , could please give me an estimation of that? Is that easy?

**Comment by fpgamcu** [comment]
An hour should be enough to perform migration.
I will also generate CubeMX project for it.

**Comment by ralcaide** [comment]
Great. Should be managed through other branch? Could I include this issue in the sprint that is ending this week? It is only one hour so should not be a problem

**Comment by fpgamcu** [comment]
Yes, sure. I can perform it today. Will you create new branch?

**Comment by ralcaide** [comment]
Yes, branch:

https://github.com/Sinapse-Energia/AP-Sinapse/tree/Commboard-V2.0-F427VG

**Comment by ralcaide** [comment]
Tested
