### ISSUE TITLE
[RF Transparent] 399; Send RF in transparent way

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/AP-Sinapse#96]
To implement 
[Transparent RF](https://github.com/Sinapse-Energia/AP-Sinapse/wiki/MQTT-Sinapse-API#send-transparent-rf---on-demmand)

**Comment by ralcaide** [comment]
To be tested through C75

**Comment by soporteHW** [comment]
Tested in FW V1.40.1 for EN device

Tested passed.
Test results here: [399; Send Transparent RF - On Demand](https://sinapseenergia.testrail.io/index.php?/tests/view/1399)
